{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "screenshot.serviceAccountName" . }}
  labels:
{{ include "screenshot.labels" . | indent 4 }}
{{- end -}}
